name: CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - uses: build/azure-pipelines/win32/continuous-build-win32@master

 
